apiVersion: v1
kind: Service
metadata:
   name: master-service
   labels:
     app: master-service
spec:
   type: NodePort
   ports:
     - port: 5001
       nodePort: 30000
   selector:
     app: master-deploy
