apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: slave-deploy
spec:
  selector:
    matchLabels:
      app: slave-deploy
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: slave-deploy
    spec:
      containers:
      - name: slave-deploy
        image: 192.168.1.220:5000/node_slave
        ports:
        - containerPort: 5002
