apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mojovm
spec:
  selector:
    matchLabels:
      app: mojovm
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mojovm
    spec:
      containers:
      - name: mojovm
        image: 192.168.1.220:5000/mojovm
        ports:
        - containerPort: 3000
