apiVersion: v1
kind: Service
metadata:
   name: mojo-service
   labels:
     app: mojo-service
spec:
   type: NodePort
   ports:
     - port: 3000
       nodePort: 30000
   selector:
     app: mojovm  
